### ISSUE TITLE
TypeError: zip argument #2 must support iteration

### ISSUE THREAD

**Issue by SeekPoint** [Cppowboy/absc#1]
ub16hp@UB16HP:~/ub16_prj/absc$ python3 -m tnet.main --mode train
  0%|             /usr/local/lib/python3.5/dist-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.                   | 0/50 [00:00<?, ?it/s]
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ub16hp/ub16_prj/absc/tnet/main.py", line 190, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/home/ub16hp/ub16_prj/absc/tnet/main.py", line 182, in main
    train(config)
  File "/home/ub16hp/ub16_prj/absc/tnet/main.py", line 80, in train
    logit.tolist(), save_fout, config)
  File "/home/ub16hp/ub16_prj/absc/tnet/main.py", line 34, in save
    print(['{}:{}'.format(t, p) for t, p in zip(polarity_list, logit)], file=fout)
TypeError: zip argument #2 must support iteration
ub16hp@UB16HP:~/ub16_prj/absc$

**Comment by Cppowboy** [comment]
It is a small bug. Because I use squeeze function in my code, when the batch size is set to 32, the last batch only has 1 sample, which makes the program crash. You can easily avoid this by using a different batch size, or modify the squeeze functions in tnet.
```
python -m tnet.main --mode train --batch 64
```
